### ISSUE TITLE
Variable in YAML

### ISSUE THREAD

**Issue by woodshoes** [boilermaker-ben/wyzeRGBW#1]
Hello!

Looking to implement on some cheap Wyze RGBWs I just got.  
What are the variable defaults for the following in the yaml?

    cold_white_color_temperature: !secret bulb_wyze_rgb_cold
    warm_white_color_temperature: !secret bulb_wyze_rgb_warm
    
 I know how to get them into the secrets file, but what are the defaults you use? 
 
 Thanks

**Comment by boilermaker-ben** [comment]
Good question! I should just put that in--I just wanted it to be a global variable. I have slightly different values than the bulb's listed Kelvin temperatures, since I automate them in Node-Red using mireds, rather than Kelvin. These are the lines I use in my "secrets" file:

```
bulb_wyze_rgb_cold: "6666.6667 K"
bulb_wyze_rgb_warm: "2500 K"
```
Those values equate to 150 to 400 mireds, which are convenient numbers to remember.

Technically, I think you should use these for the bulb's true stated specifications, but I haven't tested these to know if there are any issues, though I doubt there would be any.
```
bulb_wyze_rgb_cold: "7000 K"
bulb_wyze_rgb_warm: "2700 K"
```
